# Generated by Django 4.1.1 on 2023-03-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=2)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=190)),
                ('exp', models.TextField(max_length=900)),
                ('skills', models.TextField(max_length=900)),
                ('file', models.FileField(upload_to='')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pendentes', 'Pendentes'), ('Visualizadas', 'Visualizadas')], max_length=15)),
            ],
        ),
    ]
