# Generated by Django 4.2 on 2023-07-07 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('produto', models.CharField(max_length=50)),
                ('compras', models.CharField(max_length=50)),
                ('vendas', models.CharField(max_length=50)),
                ('quantidade', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'M'), ('U', 'U'), ('F', 'F')], max_length=100, null=True)),
                ('contexto', models.TextField(max_length=100)),
                ('Data_Criacao', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.pessoa')),
            ],
        ),
    ]
