# Generated by Django 4.2 on 2023-06-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('img', models.ImageField(upload_to='img/')),
            ],
            options={
                'verbose_name_plural': 'CATEGORIAS',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'CONTAGEM REGRESSIVA',
            },
        ),
        migrations.CreateModel(
            name='Tiped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixo', models.CharField(max_length=50)),
                ('txt01', models.CharField(max_length=100)),
                ('txt02', models.CharField(max_length=100)),
                ('txt03', models.CharField(max_length=100)),
                ('txt04', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'EFEITO DE DIGITACAO',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='img/')),
                ('detalhes', models.TextField(blank=True, max_length=1000)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category')),
            ],
            options={
                'verbose_name_plural': 'NOTICIAS',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('comentario', models.TextField(blank=True, max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.noticia')),
            ],
            options={
                'verbose_name_plural': 'COMENTARIOS',
            },
        ),
    ]
