# Generated by Django 4.2 on 2023-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countdown',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timer', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contagem regressiva',
            },
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=80)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Inscritos',
            },
        ),
        migrations.DeleteModel(
            name='Candidatos',
        ),
    ]
