# Generated by Django 4.2 on 2023-05-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_countdown_send_delete_candidatos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Contagem regressiva',
            },
        ),
        migrations.CreateModel(
            name='Tiped',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fixo', models.CharField(max_length=50)),
                ('txt01', models.CharField(max_length=50)),
                ('txt02', models.CharField(max_length=50)),
                ('txt03', models.CharField(max_length=50)),
                ('txt04', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Efeito de digitação',
            },
        ),
        migrations.DeleteModel(
            name='Countdown',
        ),
    ]
