# Generated by Django 4.2 on 2023-05-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_timer_tiped_delete_countdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tilte', models.CharField(max_length=100)),
                ('song', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Musica do fundo',
            },
        ),
    ]
