# Generated by Django 4.2 on 2023-07-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_product_genero_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cliente',
        ),
        migrations.AddField(
            model_name='product',
            name='nome',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='telefone',
            field=models.IntegerField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='genero',
            field=models.CharField(choices=[('F', 'F'), ('M', 'M'), ('U', 'U')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='pessoa',
        ),
    ]
