# Generated by Django 4.2 on 2023-07-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_product_cliente_product_nome_product_telefone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genero',
            field=models.CharField(choices=[('M', 'M'), ('F', 'F'), ('U', 'U')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
