# Generated by Django 4.2 on 2023-05-16 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='tilte',
            new_name='title',
        ),
    ]
