# Generated by Django 4.2 on 2023-07-07 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_product_genero_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='compras',
            new_name='entradas',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='vendas',
            new_name='saidas',
        ),
    ]
