# Generated by Django 4.2 on 2023-05-17 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_song_music_music_remove_music_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='title_music',
            field=models.CharField(max_length=120),
        ),
    ]
