# Generated by Django 4.2 on 2023-05-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_music_title_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='title_music',
            field=models.CharField(max_length=100),
        ),
    ]
