# Generated by Django 4.2 on 2023-05-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_home'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='color01',
            new_name='card_color01',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='color02',
            new_name='card_color02',
        ),
    ]
