# Generated by Django 4.2 on 2023-05-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('img_padra', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Imagem Padrao',
            },
        ),
    ]
