# Generated by Django 4.2 on 2023-05-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_padrao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='padrao',
            old_name='title',
            new_name='titulo',
        ),
    ]
