# Generated by Django 4.2 on 2023-05-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_rename_title_images_titulo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='padrao',
            old_name='img_padra',
            new_name='img_padrao',
        ),
    ]
